name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd Backend
          poetry install

      # 4. Ejecutar pre-commit para análisis de código
      - name: Run pre-commit
        run: |
          cd Backend
          poetry run pre-commit run --all-files

      # 5. Ejecutar pruebas con pytest y generar reporte de cobertura
      - name: Run tests
        run: |
          cd Backend
          poetry run pytest --cov=app --cov-report=xml

      # 6. Subir reporte de cobertura a Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
