name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c칩digo
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # 3. Instalar Poetry y dependencias
      - name: Install Poetry and dependencies
        working-directory: Backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # 4. Crear el archivo .env desde GitHub Secrets
      - name: Create .env file
        working-directory: Backend
        run: |
          echo "openai_api_key=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "model=${{ secrets.MODEL }}" >> .env
          echo "max_tokens=${{ secrets.MAX_TOKENS }}" >> .env
          echo "temperature=${{ secrets.TEMPERATURE }}" >> .env
          echo "number_of_vectorial_results=${{ secrets.NUMBER_OF_VECTORIAL_RESULTS }}" >> .env
          echo "secret_key=${{ secrets.SECRET_KEY }}" >> .env
          echo "algorithm=${{ secrets.ALGORITHM }}" >> .env
          echo "access_token_expire_minutes=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env
          echo "mongodb_uri=${{ secrets.MONGODB_URI }}" >> .env
          echo "mongodb_name=${{ secrets.MONGODB_NAME }}" >> .env
          echo "email_username=${{ secrets.EMAIL_USERNAME }}" >> .env
          echo "email_password=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "email_from=${{ secrets.EMAIL_FROM }}" >> .env
          echo "email_to=${{ secrets.EMAIL_TO }}" >> .env

      # 5. Verificar y cargar el archivo .env
      - name: Verify and load .env file
        working-directory: Backend
        run: |
          echo "Verificando el contenido del archivo .env:"
          cat .env
          set -a
          source .env
          set +a

      # 6. Depuraci칩n de las variables antes de ejecutar pruebas
      - name: Debug Environment Variables
        run: |
          echo "Debugging environment variables:"
          echo "MAX_TOKENS=$MAX_TOKENS"
          echo "TEMPERATURE=$TEMPERATURE"
          echo "NUMBER_OF_VECTORIAL_RESULTS=$NUMBER_OF_VECTORIAL_RESULTS"
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES"

      # 7. Ejecutar pre-commit para an치lisis de c칩digo
      - name: Run pre-commit
        working-directory: Backend
        run: poetry run pre-commit run --all-files

      # 8. Ejecutar pruebas con pytest
      - name: Run tests
        working-directory: Backend
        run: |
          export PYTHONPATH=$(pwd)
          poetry run pytest --cov=app --cov-report=xml test/cases_test.py
