name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd Backend
          poetry install

      # 4. Cargar el archivo .env desde la raíz de Backend
      - name: Set up environment variables
        run: |
          if [ -f ".env" ]; then cp .env Backend/.env; fi
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
        working-directory: Backend

      # 5. Ejecutar pre-commit para análisis de código
      - name: Run pre-commit
        run: |
          cd Backend
          poetry run pre-commit run --all-files

      # 6. Ejecutar pruebas con pytest
      - name: Run tests
        run: |
          cd Backend
          poetry run pytest --cov=app --cov-report=xml test/cases_test.py
