name: Python CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: '1.5.1'

      - name: Install dependencies
        working-directory: Backend
        run: poetry install

      - name: Set up environment variables
        working-directory: Backend
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "MODEL=text-davinci-003" >> $GITHUB_ENV
          echo "MAX_TOKENS=100" >> $GITHUB_ENV
          echo "TEMPERATURE=0.7" >> $GITHUB_ENV
          echo "NUMBER_OF_VECTORIAL_RESULTS=5" >> $GITHUB_ENV
          echo "ALGORITHM=HS256" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> $GITHUB_ENV
          echo "MONGODB_URI=mongodb://localhost:27017/testdb" >> $GITHUB_ENV
          echo "MONGODB_NAME=testdb" >> $GITHUB_ENV
          echo "EMAIL_USERNAME=test_email@example.com" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "EMAIL_FROM=from@example.com" >> $GITHUB_ENV
          echo "EMAIL_TO=to@example.com" >> $GITHUB_ENV
          echo "PYTHONPATH=${{ github.workspace }}/Backend" >> $GITHUB_ENV

      - name: Run pre-commit
        working-directory: Backend
        run: poetry run pre-commit run --all-files

      - name: Run tests
        working-directory: Backend
        env:
          PYTHONPATH: ${{ github.workspace }}/Backend
        run: |
          poetry run pytest --cov=app --cov-report=xml test/cases_test.py

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: Backend/coverage.xml
